Chocolate.Project/Controllers/CandidateController.cs
using Chocolate.Business.Services.Interfaces;
using Chocolate.DataAccess.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace ChocolateProject.Controllers
{
    [Authorize(Roles = "Admin, HR")]
    public class CandidateController : BaseController
    {
        private readonly ICandidateService _service;

        public CandidateController(ICandidateService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetCandidate(id);


            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = await _service.GetRelatedEntities();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CandidateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in Request.Form.Files)
                {
                    var memoryStream = new MemoryStream();
                    file.CopyTo(memoryStream);
                    viewModel.CV = memoryStream.ToArray();
                    viewModel.FileName = file.FileName;
                }

                var candidate = await _service.CreateCandidate(viewModel);

                await _service.CreateCandidateInfo(viewModel, candidate.Id);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetCandidate(id);


            if (viewModel == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CandidateViewModel viewModel)
        {
            if(id != viewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _service.UpdateCandidate(viewModel, id);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetCandidate(id);


            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteCandidate(id);

            return RedirectToAction(nameof(Index));
        }

        public async Task<FileContentResult> Download(int id)
        {
            var file = await _service.GetFile(id);
            return File(file.FileStream, "application/force-download", file.FileName);
        }

    }
}

Chocolate.Project/Views/Candidate/Create.cshtml
@using Chocolate.DataAccess.Models.Enums
@model Chocolate.DataAccess.ViewModels.CandidateViewModel

@{
    ViewData["Title"] = "Candidates";
}

@section Styles{
    <link rel="stylesheet" href="~/assets/libs/dropify/dropify.min.css" type="text/css" />
}

<h2>Create new Candidate</h2>
<hr />
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="p-2">
                    <form asp-action="Create" enctype="multipart/form-data">

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label" asp-for="FirstName">First Name</label>
                            <div class="col-md-10">
                                <input asp-for="FirstName" class="form-control">
                            </div>
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label" asp-for="LastName">Last Name</label>
                            <div class="col-md-10">
                                <input asp-for="LastName" class="form-control">
                            </div>
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label" asp-for="DateOfBirth">Date of Birth</label>
                            <div class="col-md-10">
                                <input type="date" value="" asp-for="DateOfBirth" class="form-control" />
                            </div>
                            <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Phone.Number" class="col-md-2 col-form-label">Phone Number</label>
                            <div class="col-md-8">
                                <input type="text" id="simpleinput" asp-for="Phone.Number" class="form-control" />
                            </div>
                            <div class="col-md-2">
                                <select asp-for="Phone.PhoneType" class="form-control" asp-items="Html.GetEnumSelectList<PhoneType>()"></select>
                            </div>
                            <span asp-validation-for="Phone.Number" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Email.Mail" class="col-md-2 col-form-label">Email</label>
                            <div class="col-md-8">
                                <input type="text" id="simpleinput" asp-for="Email.Mail" class="form-control" />
                            </div>
                            <div class="col-md-2">
                                <select asp-for="Email.MailType" class="form-control" asp-items="Html.GetEnumSelectList<MailType>()"></select>
                            </div>
                            <span asp-validation-for="Email.Mail" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Address.Location" class="col-md-2 col-form-label">Street Name</label>
                            <div class="col-md-7">
                                <input type="text" id="simpleinput" asp-for="Address.Location" class="form-control" />
                            </div>


                            <label asp-for="Address.AddressNumber" class="col-md-1 col-form-label">Street Number</label>
                            <div class="col-md-2">
                                <input type="text" id="simpleinput" asp-for="Address.AddressNumber" class="form-control" />
                            </div>
                            <span asp-validation-for="Address.Location" class="text-danger"></span>
                            <span asp-validation-for="Address.AddressNumber" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Address.Country" class="col-md-2 col-form-label">Country</label>
                            <div class="col-md-2">
                                <input type="text" id="simpleinput" asp-for="Address.Country" class="form-control" />
                            </div>


                            <label asp-for="Address.PostCode" class="col-md-1 col-form-label">Postal Code</label>
                            <div class="col-md-1">
                                <input type="text" id="simpleinput" asp-for="Address.PostCode" class="form-control" />
                            </div>


                            <label asp-for="Address.Comments" class="col-md-1 col-form-label">Comments</label>
                            <div class="col-md-5">
                                <input type="text" id="simpleinput" asp-for="Address.Comments" class="form-control" />
                            </div>
                            <span asp-validation-for="Address.PostCode" class="text-danger"></span>
                            <span asp-validation-for="Address.Country" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label" asp-for="PositionId">Department</label>
                            <div class="col-md-10">
                                <select asp-for="PositionId" class="form-control" asp-items="@(new SelectList(Model.Positions,"Id","Name"))"></select>
                            </div>
                            <span asp-validation-for="PositionId" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label" asp-for="CV">CV</label>
                            <div class="col-md-10">
                                <input type="file" class="dropify" id="CV" asp-for="CV" data-height="250">
                            </div>
                            <span asp-validation-for="CV" class="text-danger"></span>
                        </div>

                        <button type="submit" class="btn btn-bordered-primary waves-effect  width-md waves-light">Submit</button>
                        <a asp-action="Index" class="btn btn-lighten-primary waves-effect waves-primary width-md">Back to List</a>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/assets/libs/dropify/dropify.min.js"></script>
    <script src="~/assets/js/pages/form-fileupload.init.js"></script>
}

Chocolate.Project/Views/Candidate/Delete.cshtml
@model Chocolate.DataAccess.ViewModels.CandidateViewModel

@{
    ViewData["Title"] = "Candidates";
}


<h2>Are you sure you want to delete this Candidate?</h2>
<hr />
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="p-2">
                    <form>

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label" asp-for="FirstName">First Name</label>
                            <div class="col-md-10">
                                <input readonly="readonly" asp-for="FirstName" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label" asp-for="LastName">Last Name</label>
                            <div class="col-md-10">
                                <input readonly="readonly" asp-for="LastName" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label asp-for="DateOfBirth" class="col-md-2 col-form-label">Date Of Birth</label>
                            <div class="col-md-10">
                                <input asp-for="DateOfBirth" class="form-control" readonly="readonly" />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Phone.Number" class="col-md-2 col-form-label">Phone Number</label>
                            <div class="col-md-8">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Phone.Number" class="form-control" />
                            </div>
                            <div class="col-md-2">
                                <input asp-for="Phone.PhoneType" readonly="readonly" class="form-control">
                            </div>
                            <span asp-validation-for="Phone.Number" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Email.Mail" class="col-md-2 col-form-label">Email</label>
                            <div class="col-md-8">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Email.Mail" class="form-control" />
                            </div>
                            <div class="col-md-2">
                                <input asp-for="Email.MailType" readonly="readonly" class="form-control">
                            </div>
                            <span asp-validation-for="Email.Mail" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Address.Location" class="col-md-2 col-form-label">Street Name</label>
                            <div class="col-md-7">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Address.Location" class="form-control" />
                            </div>
                            <span asp-validation-for="Address.Location" class="text-danger"></span>

                            <label asp-for="Address.AddressNumber" class="col-md-1 col-form-label">Street Number</label>
                            <div class="col-md-2">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Address.AddressNumber" class="form-control" />
                            </div>
                            <span asp-validation-for="Address.AddressNumber" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Address.Country" class="col-md-2 col-form-label">Country</label>
                            <div class="col-md-2">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Address.Country" class="form-control" />
                            </div>
                            <span asp-validation-for="Address.Country" class="text-danger"></span>

                            <label asp-for="Address.PostCode" class="col-md-1 col-form-label">Postal Code</label>
                            <div class="col-md-1">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Address.PostCode" class="form-control" />
                            </div>
                            <span asp-validation-for="Address.PostCode" class="text-danger"></span>

                            <label asp-for="Address.Comments" class="col-md-1 col-form-label">Comments</label>
                            <div class="col-md-5">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Address.Comments" class="form-control" />
                            </div>
                        </div>

                        
                        <div class="form-group">
                            <div class="custom-control custom-switch">
                                <input asp-for="IsBlacklisted" class="custom-control-input" disabled />
                                <label class="custom-control-label" asp-for="IsBlacklisted">Is The Candidate Blacklisted?</label>
                            </div>
                        </div>
                    </form>

                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Delete" class="btn btn-bordered-danger waves-effect  width-md waves-light">
                        <a asp-action="Index" class="btn btn-lighten-primary waves-effect waves-primary width-md">Back to List</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

Chocolate.Project/Views/Candidate/Details.cshtml
@model Chocolate.DataAccess.ViewModels.CandidateViewModel

@{
    ViewData["Title"] = "Candidates";
}

<h2>Candidate Details</h2>
<hr />
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="p-2">
                    <form asp-action="Edit">

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label" asp-for="FirstName">First Name</label>
                            <div class="col-md-10">
                                <input readonly="readonly" asp-for="FirstName" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label" asp-for="LastName">Last Name</label>
                            <div class="col-md-10">
                                <input readonly="readonly" asp-for="LastName" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label asp-for="DateOfBirth" class="col-md-2 col-form-label">Date Of Birth</label>
                            <div class="col-md-10">
                                <input asp-for="DateOfBirth" class="form-control" readonly="readonly" />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Phone.Number" class="col-md-2 col-form-label">Phone Number</label>
                            <div class="col-md-8">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Phone.Number" class="form-control" />
                            </div>
                            <div class="col-md-2">
                                <input asp-for="Phone.PhoneType" readonly="readonly" class="form-control">
                            </div>
                            <span asp-validation-for="Phone.Number" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Email.Mail" class="col-md-2 col-form-label">Email</label>
                            <div class="col-md-8">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Email.Mail" class="form-control" />
                            </div>
                            <div class="col-md-2">
                                <input asp-for="Email.MailType" readonly="readonly" class="form-control">
                            </div>
                            <span asp-validation-for="Email.Mail" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Address.Location" class="col-md-2 col-form-label">Street Name</label>
                            <div class="col-md-7">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Address.Location" class="form-control" />
                            </div>
                            <span asp-validation-for="Address.Location" class="text-danger"></span>

                            <label asp-for="Address.AddressNumber" class="col-md-1 col-form-label">Street Number</label>
                            <div class="col-md-2">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Address.AddressNumber" class="form-control" />
                            </div>
                            <span asp-validation-for="Address.AddressNumber" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Address.Country" class="col-md-2 col-form-label">Country</label>
                            <div class="col-md-2">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Address.Country" class="form-control" />
                            </div>
                            <span asp-validation-for="Address.Country" class="text-danger"></span>

                            <label asp-for="Address.PostCode" class="col-md-1 col-form-label">Postal Code</label>
                            <div class="col-md-1">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Address.PostCode" class="form-control" />
                            </div>
                            <span asp-validation-for="Address.PostCode" class="text-danger"></span>

                            <label asp-for="Address.Comments" class="col-md-1 col-form-label">Comments</label>
                            <div class="col-md-5">
                                <input type="text" readonly="readonly" id="simpleinput" asp-for="Address.Comments" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label">Position</label>
                            <div class="col-md-10">
                                <input readonly="readonly" asp-for="Position.Name" class="form-control" />
                            </div>
                        </div>

                        
                        @if (Model.FileName != null)
                        {
                            <div class="form-group row">
                                <label class="col-md-2 col-form-label">Download CV</label>
                                <div class="col-md-10">
                                    <a data-toggle="tooltip" title="Download Attachment" class="btn btn-lighten-primary waves-effect waves-primary width-md" href="@Url.Action("Download","Candidate",new {id = Model.Id })"><i class="fa fa-download"></i></a>
                                </div>
                            </div>
                        }

                        <div class="form-group">
                            <div class="custom-control custom-switch">
                                <input asp-for="IsBlacklisted" class="custom-control-input" disabled />
                                <label class="custom-control-label" asp-for="IsBlacklisted">Is The Candidate Blacklisted?</label>
                            </div>
                        </div>

                        <div>
                            <a asp-action="Edit" class="btn btn-lighten-primary waves-effect waves-primary width-md" asp-route-id="@Model.Id">Edit</a>
                            <a asp-action="Index" class="btn btn-lighten-primary waves-effect waves-primary width-md">Back to List</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Chocolate.Project/Views/Candidate/Edit.cshtml
@using Chocolate.DataAccess.Models.Enums
@model Chocolate.DataAccess.ViewModels.CandidateViewModel

@{
    ViewData["Title"] = "Candidates";
}

<h2>Edit Candidate</h2>
<hr />
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="p-3">
                    <form asp-action="Edit">

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label" asp-for="FirstName">First Name</label>
                            <div class="col-md-10">
                                <input asp-for="FirstName" class="form-control" readonly="readonly" />
                            </div>
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label" asp-for="LastName">Last Name</label>
                            <div class="col-md-10">
                                <input asp-for="LastName" class="form-control" readonly="readonly" />
                            </div>
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="DateOfBirth" class="control-label col-md-2">Date Of Birth</label>
                            <div class="col-md-10">
                                <input asp-for="DateOfBirth" class="form-control" readonly="readonly" />
                            </div>
                            <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Phone.Number" class="col-md-2 col-form-label">Phone Number</label>
                            <div class="col-md-8">
                                <input type="text" id="simpleinput" asp-for="Phone.Number" class="form-control"  readonly="readonly"/>
                            </div>
                            <div class="col-md-2">
                                <select asp-for="Phone.PhoneType" class="form-control" asp-items="Html.GetEnumSelectList<PhoneType>()" readonly="readonly"></select>
                            </div>
                            <span asp-validation-for="Phone.Number" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Email.Mail" class="col-md-2 col-form-label">Email</label>
                            <div class="col-md-8">
                                <input type="text" id="simpleinput" asp-for="Email.Mail" class="form-control" readonly="readonly" />
                            </div>
                            <div class="col-md-2">
                                <select asp-for="Email.MailType" class="form-control" asp-items="Html.GetEnumSelectList<MailType>()" readonly="readonly"></select>
                            </div>
                            <span asp-validation-for="Email.Mail" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Address.Location" class="col-md-2 col-form-label">Street Name</label>
                            <div class="col-md-7">
                                <input type="text" id="simpleinput" asp-for="Address.Location" class="form-control"  readonly="readonly"/>
                            </div>
                            <span asp-validation-for="Address.Location" class="text-danger"></span>

                            <label asp-for="Address.AddressNumber" class="col-md-1 col-form-label">Street Number</label>
                            <div class="col-md-2">
                                <input type="text" id="simpleinput" asp-for="Address.AddressNumber" class="form-control"  readonly="readonly"/>
                            </div>
                            <span asp-validation-for="Address.AddressNumber" class="text-danger"></span>
                        </div>

                        <div class="form-group row">
                            <label asp-for="Address.Country" class="col-md-2 col-form-label">Country</label>
                            <div class="col-md-2">
                                <input type="text" id="simpleinput" asp-for="Address.Country" class="form-control"  readonly="readonly"/>
                            </div>
                            <span asp-validation-for="Address.Country" class="text-danger"></span>

                            <label asp-for="Address.PostCode" class="col-md-1 col-form-label">Postal Code</label>
                            <div class="col-md-1">
                                <input type="text" id="simpleinput" asp-for="Address.PostCode" class="form-control"  readonly="readonly"/>
                            </div>
                            <span asp-validation-for="Address.PostCode" class="text-danger"></span>

                            <label asp-for="Address.Comments" class="col-md-1 col-form-label">Comments</label>
                            <div class="col-md-5">
                                <input type="text" id="simpleinput" asp-for="Address.Comments" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group row">
                            <input asp-for="CV" type="hidden" class="form-control" />
                            <span asp-validation-for="CV" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <div class="custom-control custom-switch">
                                <input type="checkbox" class="custom-control-input" asp-for="IsBlacklisted" />
                                <label class="custom-control-label" asp-for="IsBlacklisted">Is The Candidate Blacklisted?</label>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-bordered-primary waves-effect  width-md waves-light">Save</button>
                        <a asp-action="Index" class="btn btn-lighten-primary waves-effect waves-primary width-md">Back to List</a>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}