Chocolate.Project/Controllers/LeaveController.cs
using Chocolate.Business.Services.Interfaces;
using Chocolate.DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Chocolate.DataAccess.ViewModels;
using System.IO;

namespace ChocolateProject.Controllers
{
    
    public class LeaveController : BaseController
    {
        private readonly ILeaveService _service;

        public LeaveController(ILeaveService service)
        {
            _service = service;
        }

        
        public IActionResult MyLeaves()
        {
            return View();
        }

        [Authorize(Roles = "DepartmentHead")]
        public IActionResult MyApprovals()
        {
            return View();
        }

        [Authorize(Roles = "DepartmentHead")]
        public async Task<IActionResult> Approve(int id)
        {
            await _service.ApproveLeave(id, User);
            return View(nameof(MyApprovals));
        }

        [Authorize(Roles = "DepartmentHead")]
        public async Task<IActionResult> Reject(int id)
        {
            await _service.RejectLeave(id, User);
            return View(nameof(MyApprovals));
        }

        public async Task<IActionResult> Details(int? id, bool approve = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveViewModel = await _service.GetLeaveWithIncludes(id);
            leaveViewModel.Approve = approve;

            if (leaveViewModel == null)
            {
                return NotFound();
            }

            return View(leaveViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LeaveViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateLeave(viewModel, User, Request);

                return RedirectToAction(nameof(MyLeaves));
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Leave leave)
        {
            if (id != leave.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _service.UpdateLeave(leave);

                return RedirectToAction(nameof(MyLeaves));
            }

            return View(leave);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteLeave(id);

            return RedirectToAction(nameof(MyLeaves));
        }

        public async Task<FileContentResult> Download(int id)
        {
            var file = await _service.GetFile(id);
            return File(file.FileStream, "application/force-download", file.FileName);
        }
    }
}

Chocolate.Project/Controllers/OfferController.cs
using Chocolate.Business.Services.Interfaces;
using Chocolate.DataAccess.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ChocolateProject.Controllers
{
    [Authorize(Roles = "Admin,Accounting")]
    public class OfferController : BaseController
    {
        private readonly IOfferService _service;

        public OfferController(IOfferService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetOfferWithIncludes(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = await _service.GetRelatedEntities();

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OfferViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateOffer(viewModel);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetOffer(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, OfferViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateOffer(viewModel);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetOfferWithIncludes(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteOffer(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Chocolate.Project/Controllers/OrderController.cs
using Chocolate.Business.Services.Interfaces;
using Chocolate.DataAccess.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ChocolateProject.Controllers
{
    [Authorize(Roles = "Admin,Accounting")]
    public class OrderController : BaseController
    {
        private readonly IOrderService _service;

        public OrderController(IOrderService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetOrderWithIncludes(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = await _service.GetRelatedEntities();

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OrderViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateOrder(viewModel);
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetOrderWithIncludes(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, OrderViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateOrder(viewModel);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetOrderWithIncludes(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteOrder(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

Chocolate.Project/Controllers/ShelfController.cs
using Chocolate.Business.Services.Interfaces;
using Chocolate.DataAccess.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ChocolateProject.Controllers
{
    [Authorize(Roles = "Admin,Warehouse")]
    public class ShelfController : BaseController
    {
        private readonly IShelfService _service;

        public ShelfController(IShelfService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetShelf(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = await _service.GetRelatedEntities();

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ShelfViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateShelf(viewModel);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetShelf(id);

            if (viewModel == null)
            {
                return NotFound();
            }
            
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ShelfViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateShelf(id, viewModel);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetShelf(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteShelf(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

Chocolate.Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lozan</title>
    <link rel="stylesheet" href="~/assets/images/favicon.ico" />
    @RenderSection("Styles", false)
    <link rel="stylesheet" href="~/assets/css/bootstrap-dark.min.css" />
    <link rel="stylesheet" href="~/assets/css/icons.min.css" />
    <link rel="stylesheet" href="~/assets/css/app-dark.min.css" />
    <link rel="icon" type="image/png" href="~/Images/favicon-16x16.png" />
</head>
<body>
    <!-- Begin page -->
    <div id="wrapper">

        <!-- Topbar Start -->
        @*@await Html.PartialAsync("_TopBar")*@
        @{ await Html.RenderPartialAsync("_TopBar");}
        @*<partial name="~/Shared/_TopBar.cshtml" />*@

        <!-- ========== Left Sidebar Start ========== -->
        @await Html.PartialAsync("_SideMenu")
        <!-- Left Sidebar End -->
        <div class="content-page">
            <div class="content">
                <!-- Start Content-->
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="text-md-center footer-links d-none d-sm-block">
                &copy; 2021 - Lozan - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </div>
    </footer>

    <script src="~/assets/js/vendor.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/assets/js/app.min.js"></script>
</body>
</html>

Chocolate.Project/Views/Shared/_SideMenu.cshtml
<div class="left-side-menu">

    <div class="slimscroll-menu">

        <!--- Sidemenu -->
        <div id="sidebar-menu">

            <ul class="metismenu" id="side-menu">

                @if (User.IsInRole("Admin"))
                {
                    <li class="menu-title">Management</li>

                    <li>
                        <a asp-controller="Department" asp-action="Index">
                            <i class="fas fa-briefcase"></i>
                            <span> Departments </span>
                        </a>
                    </li>

                }

                @if (User.IsInRole("Admin") || User.IsInRole("HR") || User.IsInRole("DepartmentHead"))
                {
                    <li class="menu-title">Human Resources</li>

                    <li>
                        <a asp-controller="Employee" asp-action="Index">
                            <i class="fas fa-users"></i>
                            <span> Employees </span>
                        </a>
                    </li>

                }


                @if (User.Identity.IsAuthenticated)
                {
                    <li>
                        <a href="#" aria-expanded="false">
                            <i class="fas fa-calendar-alt"></i>
                            <span>Leaves</span>
                            <span class="menu-arrow"></span>
                        </a>
                        <ul class="nav-second-level" aria-expanded="false">

                            <li>
                                <a asp-controller="Leave" asp-action="Create">
                                    <i class="far fa-calendar-plus"></i>
                                    <span>New Leave</span>
                                </a>
                            </li>

                            <li>
                                <a asp-controller="Leave" asp-action="MyLeaves">
                                    <i class="fas fa-folder-open"></i>
                                    <span>My Leaves </span>
                                </a>
                            </li>


                            @if (User.IsInRole("DepartmentHead"))
                            {
                                <li>
                                    <a asp-controller="Leave" asp-action="MyApprovals">
                                        <i class="fas fa-check-square"></i>
                                        <span>My Approvals</span>
                                    </a>
                                </li>
                            }

                        </ul>
                    </li>
                }



                @if (User.IsInRole("Admin") || User.IsInRole("HR"))
                {
                    <li>
                        <a href="#" aria-expanded="false">
                            <i class="fas fa-handshake"></i>
                            <span>Recruitment</span>
                            <span class="menu-arrow"></span>
                        </a>
                        <ul class="nav-second-level" aria-expanded="false">

                            <li>
                                <a asp-controller="Position" asp-action="Index">
                                    <i class="fas fa-street-view"></i>
                                    <span> Positions </span>
                                </a>
                            </li>

                            <li>
                                <a asp-controller="Candidate" asp-action="Index">
                                    <i class="fas fa-portrait"></i>
                                    <span> Candidates </span>
                                </a>
                            </li>

                            <li>
                                <a asp-controller="Interview" asp-action="Index">
                                    <i class="fas fa-comments"></i>
                                    <span> Interviews </span>
                                </a>
                            </li>
                        </ul>
                    </li>
                }
                @if (User.IsInRole("Admin") || User.IsInRole("Accounting"))
                {
                    <li class="menu-title">Shop</li>

                    <li>
                        <a asp-controller="Customer" asp-action="Index">
                            <i class="fas  fa-address-card"></i>
                            <span> Customers </span>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="Order" asp-action="Index">
                            <i class="fas fa-shopping-basket"></i>
                            <span> Orders </span>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="Purchase" asp-action="Index">
                            <i class="fas fa-wallet"></i>
                            <span> Purchases </span>
                        </a>
                    </li>

                    <li>
                        <a href="#" aria-expanded="false">
                            <i class="fas fa-coins"></i>
                            <span>Pricing</span>
                            <span class="menu-arrow"></span>
                        </a>
                        <ul class="nav-second-level" aria-expanded="false">
                            <li>
                                <a asp-controller="Discount" asp-action="Index">
                                    <i class="fas fa-piggy-bank"></i>
                                    <span> Discounts </span>
                                </a>
                            </li>

                            <li>
                                <a asp-controller="DiscountLevel" asp-action="Index">
                                    <i class="fas fa-wave-square"></i>
                                    <span> Discount Levels </span>
                                </a>
                            </li>

                            <li>
                                <a asp-controller="Offer" asp-action="Index">
                                    <i class="fas fa-money-bill-wave"></i>
                                    <span> Offers </span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="OfferItem" asp-action="Index">
                                    <i class="fas fa-chart-bar"></i>
                                    <span> Offer Items </span>
                                </a>
                            </li>
                        </ul>
                    </li>
                }

                @if (User.IsInRole("Admin") || User.IsInRole("Warehouse"))
                {
                    <li class="menu-title">Repository</li>

                    <li>
                        <a asp-controller="Product" asp-action="Index">
                            <i class="fas  fa-cookie-bite"></i>
                            <span> Products </span>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="RawMaterial" asp-action="Index">
                            <i class="fas fa-mortar-pestle"></i>
                            <span> Raw Material </span>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="Supplier" asp-action="Index">
                            <i class="fas fa-truck-loading"></i>
                            <span> Suppliers </span>
                        </a>
                    </li>
                }

                @if (User.IsInRole("Admin") || User.IsInRole("Warehouse"))
                {
                    <li>
                        <a href="#" aria-expanded="false">
                            <i class="fas fa-people-carry"></i>
                            <span>Storage</span>
                            <span class="menu-arrow"></span>
                        </a>
                        <ul class="nav-second-level" aria-expanded="false">

                            <li>
                                <a asp-controller="Warehouse" asp-action="Index">
                                    <i class="fas fa-warehouse"></i>
                                    <span> Warehouses </span>
                                </a>
                            </li>

                            <li>
                                <a asp-controller="StorageUnit" asp-action="Index">
                                    <i class="fas fa-boxes"></i>
                                    <span> Storage Units </span>
                                </a>
                            </li>

                            <li>
                                <a asp-controller="Sector" asp-action="Index">
                                    <i class="fas fa-box"></i>
                                    <span> Sectors </span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Shelf" asp-action="Index">
                                    <i class="fas fa-layer-group"></i>
                                    <span> Shelves </span>
                                </a>
                            </li>
                        </ul>
                    </li>
                }

                @if (User.IsInRole("Admin"))
                {
                    <li class="menu-title">Administrations</li>

                    <li>
                        <a href="#" aria-expanded="false">
                            <i class="fas fa-users-cog"></i>
                            <span>Users</span>
                            <span class="menu-arrow"></span>
                        </a>
                        <ul class="nav-second-level" aria-expanded="false">

                            <li>
                                <a asp-controller="Administration" asp-action="UserIndex">
                                    <i class="fas fa-user-cog"></i>
                                    <span> All Users </span>
                                </a>
                            </li>

                            <li>
                                <a asp-controller="Account" asp-action="Register">
                                    <i class="fas fa-user-plus"></i>
                                    <span> Register User </span>
                                </a>
                            </li>
                        </ul>

                    </li>

                    <li>
                        <a asp-controller="Administration" asp-action="RoleIndex">
                            <i class="fas fa-user-lock"></i>
                            <span>Roles</span>
                        </a>
                    </li>
                }
            </ul>
        </div>
        <!-- End Sidebar -->

        <div class="clearfix"></div>
    </div>
    <!-- Sidebar -left -->
</div>

Chocolate.Project/Views/Shared/_TopBar.cshtml
<div class="navbar-custom">
    <ul class="list-unstyled topnav-menu float-right mb-0">

        <li class="dropdown notification-list">

            @if (User.Identity.IsAuthenticated)
            {
                <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                    <img src="~/assets/images/users/user-12.jpg" alt="user-image" class="rounded-circle">
                    <span class="pro-user-name ml-1">
                        Welcome @Context.User.Identity.Name! <i class="mdi mdi-chevron-down"></i>
                    </span>
                </a>
            }
            else
            {
                <a asp-controller="Account" asp-action="Login" class="dropdown-item notify-item">
                    <i class="fas fa-user-lock"></i>
                    <span>Login</span>
                </a>
            }
            <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                <!-- item-->
                <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Leaving so soon?</h6>
                </div>

                @if (User.Identity.IsAuthenticated)
                {
                    <a asp-controller="Account" asp-action="Logout" class="dropdown-item notify-item">
                        <i class="fe-log-out"></i>
                        <span>Logout</span>
                    </a>
                }
            </div>
        </li>
    </ul>

    <!-- LOGO -->
    <div class="logo-box">
        <a asp-controller="Home" asp-action="Index" class="logo logo-dark text-center">
            <span class="logo-lg">
                <img src="~/Images/logo-brown.png" alt="" height="50">
            </span>
            <span class="logo-sm">
                <img src="~/Images/L_Brown1.png" alt="" height="24">
            </span>
        </a>
        <a href="index.html" class="logo logo-light text-center">
            <span class="logo-lg">
                <img src="~/Images/logo-brown.png" alt="" height="16">
            </span>
            <span class="logo-sm">
                <img src="~/Images/logo-brown.png" alt="" height="24">
            </span>
        </a>
    </div>

    <ul class="list-unstyled topnav-menu topnav-menu-left mb-0">
        <li>
            <button class="button-menu-mobile disable-btn waves-effect">
                <i class="fe-menu"></i>
            </button>
        </li>
    </ul>
</div>