Chocolate.Project/Controllers/CustomerController.cs
using Chocolate.Business.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using Chocolate.DataAccess.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace ChocolateProject.Controllers
{
    [Authorize(Roles = "Admin,Accounting")]
    public class CustomerController : BaseController
    {
        private readonly ICustomerService _service;

        public CustomerController(ICustomerService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetDetails(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        public IActionResult Create()
        {
            var viewModel = new CustomerViewModel();
            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CustomerViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var customer = await _service.CreateCustomer(viewModel);

                await _service.CreateCustomerInfo(viewModel, customer.Id);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetDetails(id);

            if(viewModel == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CustomerViewModel viewModel)
        {
            if (id != viewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _service.UpdateCustomer(viewModel, id);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetDetails(id);

            if (viewModel == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteCustomer(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Chocolate.Project/Controllers/EmployeeController.cs
using Chocolate.Business.Services.Interfaces;
using Chocolate.DataAccess.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace ChocolateProject.Controllers
{
    //authorize annotation allows certain roles to access this controller
    [Authorize(Roles = "Admin, HR, DepartmentHead")]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _service;

        //Dependency Injection --> resolved with AutoFac
        public EmployeeController(IEmployeeService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Details(int id)
        {
            var viewModel = await _service.GetDetails(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = await _service.CreateViewModel();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var employee = await _service.CreateEmployee(viewModel);

                await _service.CreateEmployeeInfo(viewModel, employee.Id);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var viewModel = await _service.GetDetails(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EmployeeViewModel viewModel)
        {
            if (id != viewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _service.UpdateEmployee(viewModel, id);

                return RedirectToAction(nameof(Index));
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var employee = await _service.GetDetails(id);

            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteEmployee(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

Chocolate.Project/Controllers/HomeController.cs
using Chocolate.DataAccess;
using Chocolate.DataAccess.ViewModels;
using ChocolateProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Linq;

namespace ChocolateProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ChocolateDbContext _context;

        public HomeController(ChocolateDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var viewModel = new HomeViewModel
            {
                Departments = _context.Departments.Count(),
                Candidates = _context.Candidates.Count(),
                Customers = _context.Customers.Count(),
                Employees = _context.Employees.Count(),
                Orders = _context.Orders.Count(),
                Positions = _context.Positions.Count(),
                Products = _context.Products.Count(),
                Purchases = _context.Purchases.Count(),
                RawMaterials = _context.RawMaterials.Count(),
                StorageUnits = _context.StorageUnits.Count(),
                Suppliers = _context.Suppliers.Count(),
                Warehouses = _context.Warehouses.Count()
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult GetAllMeetings(HomeViewModel viewModel)
        {
            return View(viewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Chocolate.Project/Controllers/OrderController.cs
using Chocolate.Business.Services.Interfaces;
using Chocolate.DataAccess.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ChocolateProject.Controllers
{
    [Authorize(Roles = "Admin,Accounting")]
    public class OrderController : BaseController
    {
        private readonly IOrderService _service;

        public OrderController(IOrderService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetOrderWithIncludes(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = await _service.GetRelatedEntities();

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OrderViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateOrder(viewModel);
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetOrderWithIncludes(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, OrderViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateOrder(viewModel);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetOrderWithIncludes(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteOrder(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

Chocolate.Project/Controllers/ProductController.cs
using Chocolate.Business.Services.Interfaces;
using Chocolate.DataAccess.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ChocolateProject.Controllers
{
    [Authorize(Roles = "Admin,Accounting")]
    public class ProductController : BaseController
    {
        private readonly IProductService _service;

        public ProductController(IProductService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetProductWithIncludes(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = await _service.GetRelatedEntities();

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateProduct(viewModel, Request);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetProductWithIncludes(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateProduct(viewModel, Request);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _service.GetProduct(id);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteProduct(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Chocolate.Project/Views/Home/Index.cshtml
@model Chocolate.DataAccess.ViewModels.HomeViewModel

@{ ViewData["Title"] = "Home Page"; }

@section styles{
    <link href="~/assets/libs/fullcalendar/fullcalendar.min.css" rel="stylesheet" type="text/css" />
}

<div class="row">
    <div class="col-sm-12">
        <div class="card-box">

            <h4 class="header-title mt-0">Welcome!</h4>
            @if (User.IsInRole("Admin"))
            {
                <div class="row">
                    <div class="col-md-6 col-xl-3 text-center">
                        <a asp-controller="Department" asp-action="Index">
                            <div class="mt-3" dir="ltr">
                                <input data-plugin="knob" data-width="150" data-height="150"
                                       data-angleOffset="0" data-fgColor="#2A9D8F"
                                       data-bgColor="#292e39" value="@Model.Departments" data-readOnly=true />
                                <h5 class="text-muted">Departments</h5>
                            </div>
                        </a>
                    </div><!-- end col-->

                    <div class="col-md-6 col-xl-3 text-center">
                        <a asp-controller="Employee" asp-action="Index">
                            <div class="mt-3" dir="ltr">
                                <input data-plugin="knob" data-width="150" data-height="150"
                                       data-angleOffset="0" data-fgColor="#E9C46A"
                                       data-bgColor="#292e39" value="@Model.Employees" data-readOnly=true />
                                <h5 class="text-muted">Employees</h5>
                            </div>
                        </a>
                    </div><!-- end col-->

                    <div class="col-md-6 col-xl-3 text-center">
                        <a asp-controller="Position" asp-action="Index">
                            <div class="mt-3" dir="ltr">
                                <input data-plugin="knob" data-width="150" data-height="150"
                                       data-angleOffset="0" data-fgColor="#F4A261"
                                       data-bgColor="#292e39" value="@Model.Positions" data-readOnly=true />
                                <h5 class="text-muted">Positions</h5>
                            </div>
                        </a>
                    </div><!-- end col-->

                    <div class="col-md-6 col-xl-3 text-center">
                        <a asp-controller="Candidate" asp-action="Index">
                            <div class="mt-3" dir="ltr">
                                <input data-plugin="knob" data-width="150" data-height="150"
                                       data-angleOffset="0" data-fgColor="#E76F51"
                                       data-bgColor="#292e39" value="@Model.Candidates" data-readOnly=true />
                                <h5 class="text-muted">Candidates</h5>
                            </div>
                        </a>
                    </div><!-- end col-->
                </div><!-- end row -->

                <div class="row">
                    <div class="col-md-6 col-xl-3 text-center">
                        <a asp-controller="Customer" asp-action="Index">
                            <div class="mt-3" dir="ltr">
                                <input data-plugin="knob" data-width="150" data-height="150"
                                       data-angleOffset="0" data-fgColor="#CDB4DB"
                                       data-bgColor="#292e39" value="@Model.Customers" data-readOnly=true />
                                <h5 class="text-muted">Customers</h5>
                            </div>
                        </a>
                    </div><!-- end col-->

                    <div class="col-md-6 col-xl-3 text-center">
                        <a asp-controller="Order" asp-action="Index">
                            <div class="mt-3" dir="ltr">
                                <input data-plugin="knob" data-width="150" data-height="150"
                                       data-angleOffset="0" data-fgColor="#FFC8DD"
                                       data-bgColor="#292e39" value="@Model.Orders" data-readOnly=true />
                                <h5 class="text-muted">Orders</h5>
                            </div>
                        </a>
                    </div><!-- end col-->

                    <div class="col-md-6 col-xl-3 text-center">
                        <a asp-controller="Purchase" asp-action="Index">
                            <div class="mt-3" dir="ltr">
                                <input data-plugin="knob" data-width="150" data-height="150"
                                       data-angleOffset="0" data-fgColor="#FFAFCC"
                                       data-bgColor="#292e39" value="@Model.Purchases" data-readOnly=true />
                                <h5 class="text-muted">Purchases</h5>
                            </div>
                        </a>
                    </div><!-- end col-->

                    <div class="col-md-6 col-xl-3 text-center">
                        <a asp-controller="Product" asp-action="Index">
                            <div class="mt-3" dir="ltr">
                                <input data-plugin="knob" data-width="150" data-height="150"
                                       data-angleOffset="0" data-fgColor="#BDE0FE"
                                       data-bgColor="#292e39" value="@Model.Products" data-readOnly=true />
                                <h5 class="text-muted">Products</h5>
                            </div>
                        </a>
                    </div><!-- end col-->
                </div><!-- end row-->

                <div class="row">
                    <div class="col-md-6 col-xl-3 text-center">
                        <a asp-controller="RawMaterial" asp-action="Index">
                            <div class="mt-3" dir="ltr">
                                <input data-plugin="knob" data-width="150" data-height="150"
                                       data-angleOffset="0" data-fgColor="#d8e2dc"
                                       data-bgColor="#292e39" value="@Model.RawMaterials" data-readOnly=true />
                                <h5 class="text-muted">Raw Materials</h5>
                            </div>
                        </a>
                    </div><!-- end col-->

                    <div class="col-md-6 col-xl-3 text-center">
                        <a asp-controller="Supplier" asp-action="Index">
                            <div class="mt-3" dir="ltr">
                                <input data-plugin="knob" data-width="150" data-height="150"
                                       data-angleOffset="0" data-fgColor="#B56576"
                                       data-bgColor="#292e39" value="@Model.Suppliers" data-readOnly=true />
                                <h5 class="text-muted">Suppliers</h5>
                            </div>
                        </a>
                    </div><!-- end col-->

                    <div class="col-md-6 col-xl-3 text-center">
                        <a asp-controller="Warehouse" asp-action="Index">
                            <div class="mt-3" dir="ltr">
                                <input data-plugin="knob" data-width="150" data-height="150"
                                       data-angleOffset="0" data-fgColor="#E56B6F"
                                       data-bgColor="#292e39" value="@Model.Warehouses" data-readOnly=true />
                                <h5 class="text-muted">Warehouses</h5>
                            </div>
                        </a>
                    </div><!-- end col-->

                    <div class="col-md-6 col-xl-3 text-center">
                        <a asp-controller="StorageUnit" asp-action="Index">
                            <div class="mt-3" dir="ltr">
                                <input data-plugin="knob" data-width="150" data-height="150"
                                       data-angleOffset="0" data-fgColor="#EAAC8B"
                                       data-bgColor="#292e39" value="@Model.StorageUnits" data-readOnly=true />
                                <h5 class="text-muted">Storage Units</h5>
                            </div>
                        </a>
                    </div><!-- end col-->
                </div><!-- end row-->
            }

            @if (User.Identity.IsAuthenticated)
            {

                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-flex align-items-center justify-content-between">
                            <h4 class="page-title">Calendar</h4>

                            <div class="page-title-right">
                                <ol class="breadcrumb m-0">
                                </ol>
                            </div>

                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">

                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card-box">
                                    <div id="calendar"></div>
                                </div>
                            </div> <!-- end col -->
                        </div>  <!-- end row -->
                        <!-- BEGIN MODAL -->
                        <div class="modal fade none-border" id="event-modal">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title mt-0"><strong>Add Meeting</strong></h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    </div>
                                        <div class="form-group">
                                            <form id="meetingForm">
                                                <label class="col-md-2 col-form-label">Title</label>
                                                <div class="col-md-10">
                                                    <input name="Title" id="meetingTitle" class="form-control">
                                                </div>

                                                <div class="form-group">
                                                    <label class="col-md-2 col-form-label">Date</label>
                                                    <div class="col-md-10">
                                                        <input type="datetime-local" id="meetingDate" class="form-control">
                                                    </div>
                                                </div>
                                            </form>
                                        </div>

                                    <div class="modal-footer">
                                        <a id="closeBtn" class="btn btn-light waves-effect" data-dismiss="modal">Close</a>
                                        <a id="btnCreate" class="btn btn-success" style="color:white">Add</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end col-12 -->
                </div> <!-- end row -->
            }
        </div>
    </div><!-- end col-->
</div>
<!-- end row -->

@section Scripts{
    <!-- knob plugin -->
    <script src="~/assets/libs/jquery-knob/jquery.knob.min.js"></script>
    <script src="~/assets/libs/moment/moment.js"></script>
    <script src="~/assets/libs/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/assets/libs/fullcalendar/fullcalendar.min.js"></script>
    <script src="~/src/js/pages/fullcalendar.init.js"></script>

    <script>
        $('#btnCreate').click(function () {
            var title = $('#meetingTitle').val();
            var when = $('#meetingDate').val();

            $.ajax({
                type: "POST",
                url: "/api/meetings",
                data: JSON.stringify({ 'title': title, 'when': when }),
                dataType: "json",
                contentType: "application/json"
            });

            $('#event-modal').modal('hide');
            location.reload();

        });
    </script>
}